/*
 * generated by Xtext
 */
package dk.sdu.mmmi.tjep.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import dk.sdu.mmmi.tjep.ui.internal.TJActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TJExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return TJActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return TJActivator.getInstance().getInjector(TJActivator.DK_SDU_MMMI_TJEP_TJ);
	}
	
}
