/*
* generated by Xtext
*/
package dk.sdu.mmmi.tjep;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class TJUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return dk.sdu.mmmi.tjep.ui.internal.TJActivator.getInstance().getInjector("dk.sdu.mmmi.tjep.TJ");
	}
	
}
