/*
* generated by Xtext
*/
package dk.sdu.mmmi.tjep.ui.contentassist;

import dk.sdu.mmmi.tjep.ui.contentassist.AbstractTJProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class TJProposalProvider extends AbstractTJProposalProvider {

}
