/*
* generated by Xtext
*/
package dk.sdu.mmmi.tjep.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TJAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("dk/sdu/mmmi/tjep/parser/antlr/internal/InternalTJ.tokens");
	}
}
