/*
* generated by Xtext
*/
package dk.sdu.mmmi.tjep.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import dk.sdu.mmmi.tjep.services.TJGrammarAccess;

public class TJParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private TJGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected dk.sdu.mmmi.tjep.parser.antlr.internal.InternalTJParser createParser(XtextTokenStream stream) {
		return new dk.sdu.mmmi.tjep.parser.antlr.internal.InternalTJParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}
	
	public TJGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TJGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
