/*
 * generated by Xtext
 */
package dk.sdu.mmmi.tjep.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TJUiModule extends dk.sdu.mmmi.tjep.ui.AbstractTJUiModule {
	public TJUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
