/*
 * generated by Xtext
 */
package dk.sdu.mmmi.tjep;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TJRuntimeModule extends dk.sdu.mmmi.tjep.AbstractTJRuntimeModule {

}
